### PR TITLE
remove ssh keys from repo

### PR DESCRIPTION
**Pull request by r7vme**
Fixes: https://github.com/giantswarm/giantswarm/issues/3695

### CODE REVIEW

**Comment by corest** [comment]
How do we inject users then?

**Comment by calvix** [comment]
same question

**Comment by r7vme** [comment]
Here you go https://github.com/giantswarm/conveyor/pull/30

**Comment by r7vme** [comment]
And this one https://github.com/giantswarm/installations/pull/440

**Comment by r7vme** [comment]
> please update installation docs with commands how to inject users as its done in conveyor scripts

Good point. done.

Whole installation guide will be handled [here](https://github.com/giantswarm/giantswarm/issues/3638), so i'm not mentioning in this open source repo any private resources, just adding generic instructions.

**Pull request merged**
