### PR TITLE
Apply override to journald systemd unit

### PR DESCRIPTION
**Pull request by whites11**
towards: https://github.com/giantswarm/giantswarm/issues/23524#issuecomment-1285574139

needed  to overcome race condition between auditd and falco that made journald to crash.

### CODE REVIEW

**Comment by hervenicol** [comment]
Changed:
* override is now set the `ignition` way
* disabled `journal-flush` to make sure logs stay in `/run` as expected.

**Comment by hervenicol** [comment]
Tested on Gaia, everything looks good.
```bash
# No error message at login
$ opsctl ssh gaia ip-10-0-5-47.eu-central-1.compute.internal
Warning: Permanently added 'ip-10-0-5-47.eu-central-1.compute.internal' (ED25519) to the list of known hosts.
Last login: Tue Oct 25 14:55:33 UTC 2022 from 10.0.221.42 on ssh
Flatcar Container Linux by Kinvolk stable 3227.2.2 for Amazon EC2
Update Strategy: No Reboots

# No failed units
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $ systemctl list-units --failed                            
WARNING: terminal is not fully functional
Press RETURN to continue 
  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed.

# flush is disabled and masked
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $ sudo systemctl status systemd-journal-flush.service                                                                                                                              
WARNING: terminal is not fully functional
Press RETURN to continue 
○ systemd-journal-flush.service
     Loaded: masked (Reason: Unit systemd-journal-flush.service is masked.)
     Active: inactive (dead)

# storage config file and journald override file are correctly set
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $ cat /etc/systemd/journald.conf.d/storage.conf
[Journal]
Storage=volatile
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $ ls -l /etc/systemd/journald.conf.d/storage.conf          
-rw-r--r--. 1 root root 27 Oct 25 14:52 /etc/systemd/journald.conf.d/storage.conf
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $ cat /etc/systemd/system/systemd-journald.service.d/10-override.conf                                                  
[Unit]
StartLimitIntervalSec=0
[Service]
RestartSec=1

# Journal files are under `/var`
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $ sudo ls -l /run/log/journal/ec2a87ced83801c39079020511fb81ae/                                                                                                                    
total 259688
-rw-r-----. 1 root systemd-journal 25165824 Oct 25 15:30 system.journal
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:53 system@0005ebdd140e694d-eab9d737999a33d1.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:54 system@0005ebdd142180f5-476c6ccf7dd675e5.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:54 system@0005ebdd1435257a-44a02f92adfb7c0c.journal~
-rw-r-----. 1 root systemd-journal 25165824 Oct 25 14:54 system@0005ebdd1454d438-1c78ac636f7329c1.journal~
-rw-r-----. 1 root systemd-journal 16777216 Oct 25 14:55 system@0005ebdd19102a90-6dda274d2d69749e.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:55 system@0005ebdd1923292d-26ba5c2d2d8c3ae6.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:55 system@0005ebdd1936790b-dbf7438bc985e1c7.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:55 system@0005ebdd19494d88-2aec53f6392952db.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:55 system@0005ebdd195c82f9-afe59357193aac32.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:55 system@0005ebdd196ce011-f1afd56ea244ee5c.journal~
-rw-r-----. 1 root systemd-journal  8388608 Oct 25 14:55 system@0005ebdd197eb443-628ef4a07f8208a8.journal~
-rw-r-----. 1 root systemd-journal 41185264 Oct 25 14:54 system@e2b5fee65a6c4d5f81042c2623f85c03-0000000000000001-0005ebdd1454e187.journal
-rw-r-----. 1 root systemd-journal 41086616 Oct 25 14:54 system@e2b5fee65a6c4d5f81042c2623f85c03-000000000000a62e-0005ebdd15801325.journal
-rw-r-----. 1 root systemd-journal 41040296 Oct 25 14:54 system@e2b5fee65a6c4d5f81042c2623f85c03-0000000000014741-0005ebdd159bbd17.journal
WARNING: CONTROL-PLANE MASTER | giantswarm@ip-10-0-5-47 ~ $                                          
```

**Review by QuentinBisson — APPROVED** [review]
Trusting you

**Comment by hervenicol** [comment]
@whites11 , could you please review?
I can't set you as reviewer, probably because you created the PR. :shrug:

**Comment by whites11** [comment]
> @whites11 , could you please review? I can't set you as reviewer, probably because you created the PR. 🤷

Yeah, lgtm but I can't approve. If you approve I can merge and manage release though

**Review by hervenicol — APPROVED** [review]

**Pull request merged**
