### PR TITLE
Add metrics server to CPs

### PR DESCRIPTION
**Pull request by pipo02mix**
Trying to add an HPA for a component I have realized we did not have metrics server in CPs. I think it is a good idea to add it.

### CODE REVIEW

**Comment by pipo02mix** [comment]
How can I test it (I did manually)?

**Comment by corest** [comment]
@pipo02mix you can trigger terraform rollout via conveyor with your branch

**Comment by calvix** [comment]
this wont work, you created the necessary manifests but nothing is executing them 

You need to add the metrics server manifest in k8s-addons

**Comment by pipo02mix** [comment]
waiting for Azure
```
module.vnet.azurerm_subnet_network_security_group_association.worker: Still creating... [34m30s elapsed]
```

**Pull request merged**
