### PR TITLE
Fix k8s core component scraping

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/giantswarm/issues/24059

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
OK as soon as this was tested.

**Comment by QuentinBisson** [comment]
@whites11 it requires 2 additional flags so the https endpoint can be accessed, namely:
- --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
- --authorization-kubeconfig=/etc/kubernetes/scheduler.conf

It's straightforward to use it with CAPI as kubeadm provides it but does out vintage tooling provide such a file?

**Comment by whites11** [comment]
> @whites11 it requires 2 additional flags so the https endpoint can be accessed, namely:
> 
> * --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
> * --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
> 
> It's straightforward to use it with CAPI as kubeadm provides it but does out vintage tooling provide such a file?

you can try with /etc/kubernetes/kubeconfig/scheduler.yaml and /etc/kubernetes/kubeconfig/controller-manager.yaml

**Comment by QuentinBisson** [comment]
Not sure why it's failing on gollum :(


: curl localhost:8001/api/v1/namespaces/kube-system/pods/https:k8s-scheduler-master-00001x:10259/proxy/metrics
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}%

**Comment by QuentinBisson** [comment]
The double quotes around the arg value were the error but I broke gollum terraform action :( https://github.com/giantswarm/installations/actions/runs/3440615427/jobs/5739285310

Is there a way to fix it?

**Pull request merged**
