### PR TITLE
Reduce number of collectors used in node-exporter on bastions

### PR DESCRIPTION
**Pull request by corest**
Towards https://github.com/giantswarm/giantswarm/issues/14042

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
Sounds good if works for you.

**Comment by mazzy89** [comment]
Isn't easier to specify which collector we are enabling instead to specify which collector we are *enabling*? the mental process would tell me when I look at the PR or the deployed flags to go and check which are the other collectors. I agree with the direction but I see the node-exporter config as harder to read it in this specific case.

**Comment by corest** [comment]
@mazzy89 config options are ordered - first go enabled, then disabled. What is hard to read exactly?

**Comment by mazzy89** [comment]
So the only collector that we enable, they will be enabled. if we do not enable them explicitly no one of them will be enabled by default right? If this is true then I'm fine with that.

**Comment by corest** [comment]
@mazzy89 this PR changes nothing regarding how node-exporter works. Just moving explicitly enabled to explicitly disabled. We do the same in tenant clusters

**Pull request merged**
