### PR TITLE
Change back to deployment but with affinity

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/11520

### CODE REVIEW

**Comment by pipo02mix** [comment]
Tested on gauss and seal

**Comment by calvix** [comment]
file rename would be great to reflect the resource

also, we might wanna add some smart kubectl delete command for the daemonset to the `k8s-addons`

**Comment by pipo02mix** [comment]
> file rename would be great to reflect the resource

Good point 😅

**Comment by pipo02mix** [comment]
Tested on ginger

**Comment by pipo02mix** [comment]
Both e2e fails for same reason

```
TASK [defunctzombie.flatcar-bootstrap : Check if bootstrap is needed] **********
fatal: [vault1.e2etf-d5c1.************.aws.gigantic.io]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Warning: Permanently added 'vault1.e2etf-d5c1.************.aws.gigantic.io' (ECDSA) to the list of known hosts.\r\nShared connection to vault1.e2etf-d5c1.************.aws.gigantic.io closed.\r\n", "stderr_lines": ["Warning: Permanently added 'vault1.e2etf-d5c1.************.aws.gigantic.io' (ECDSA) to the list of known hosts.", "Shared connection to vault1.e2etf-d5c1.************.aws.gigantic.io closed."], "stdout": "stat: cannot stat '/root/.bootstrapped': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/root/.bootstrapped': No such file or directory"]}
```

Any idea? how I can solve it?

**Comment by corest** [comment]
Might be guessing but probably related to the user repos changes

**Pull request merged**
