### PR TITLE
Permissions for mimir bucket

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
towards https://github.com/giantswarm/roadmap/issues/2263

S3 bucket manually created on `gauss` (gauss-g8s-mimir) and need permissions for nodes to access it.

### CODE REVIEW

**Comment by hervenicol** [comment]
Some extra context for Phoenix team:
We are starting experiments for Mimir. The plan is, like Loki, to have it running on some MCs.
Like Loki, its storage is on S3.

This is an experiment for the moment, but we hope to have it running on a few clusters.
So we're doing the setup just like we did with Loki, but if you have a better idea than pushing the access rights this way, please share!

**Review by hervenicol — APPROVED** [review]
LGTM, but please wait for Phoenix approval too :wink:

**Comment by whites11** [comment]
this PR only adds permissions to the worker nodes, but on MCs the master nodes are schedulable as well so I suggest adding the same rules to the master nodes role as well

**Comment by QuantumEnigmaa** [comment]
Tested and working : 
image

Command launched from a `gauss` MC's worker node :
```
WARNING: CONTROL-PLANE WORKER | giantswarm@ip-10-0-5-177 ~ $ docker run --network host --rm -i docker.io/giantswarm/awscli:2.7.35 -- s3 ls s3://gauss-g8s-mimir                                                                                                                          
2023-04-06 13:47:51         13 test.yaml
```
Command launched from a `gauss` MC's master node : 
```

**Pull request merged**
