### PR TITLE
fix typo in journald unit fix

### PR DESCRIPTION
**Pull request by hervenicol**
Towards https://github.com/giantswarm/giantswarm/issues/23524

Same block of code in masters and workers, but a typo made it fail on workers :disappointed:

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
Aw snap!

**Comment by whites11** [comment]
@hervenicol want me to deploy in one specific MC for final validation?

**Comment by hervenicol** [comment]
> @hervenicol want me to deploy in one specific MC for final validation?

Would be great! Whichever you do first, ping me I'll do a quick check.

**Comment by whites11** [comment]
> > @hervenicol want me to deploy in one specific MC for final validation?
> 
> Would be great! Whichever you do first, ping me I'll do a quick check.

It's deployed on `gaia`, `giraffe` and `godsmack`.
Waiting your `go` to deploy everywhere

**Comment by hervenicol** [comment]
All good on `gaia`, `go` @whites11 :+1: :rocket:

**Comment by whites11** [comment]
deployed everywhere

**Pull request merged**
