### PR TITLE
limit-logs-vault

### PR DESCRIPTION
**Pull request by calvix**
we somehow forget to add this settings for vault node

### CODE REVIEW

**Comment by r7vme** [comment]
Any progress?

**Comment by calvix** [comment]
For some weird reason this dont wanna pass e2e, cant figure out  why :(

**Comment by corest** [comment]
Worth to add some sleep before destroy, ssh into vault and check what's wrong with etcd_unsecure service, which is failing due to some missing dependencies

**Comment by JosephSalisbury** [comment]
```
TASK [etcd unsecure | Ensure etcd service is running (docker container)] *******
fatal: [vault1.e2e-terraform-58f6d8.eu-central-1.aws.gigantic.io]: FAILED! => {"changed": false, "msg": "Unable to start service etcd_unsecure: A dependency job for etcd_unsecure.service failed. See 'journalctl -xe' for details.\n"}
	to retry, use: --limit @/tmp/tmp.jYXFF0tb77/hive/bootstrap1.retry
```

**Comment by JosephSalisbury** [comment]
@calvix i take this now

**Comment by JosephSalisbury** [comment]
ssh seems to broken
```
[  138.323611] extend-filesystems[  138.333946] EXT4-fs (xvda9): resizing filesystem from 553472 to 1489915 blocks
[801]: [[0;1;31mFAILED[0m] Failed to start CoreOS Metadata Agent (SSH Keys).
See 'systemctl status coreos-metadata-sshkeys@core.service' for details.resize2fs 1.43.3 (04-Sep-2016)
```
working out how to get ssh key in w/ ignition

**Comment by r7vme** [comment]
This PR related to postmortem that i took over from Joe, so will push that forward.

**Pull request merged**
