### PR TITLE
Add featuregate for CustomResource Subresources

### PR DESCRIPTION
**Pull request by tuommaki**
In order to be able to use subresources in custom resources, a
feature gate flag must be added to k8s apiserver.

https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#subresources

This is first used in cluster-operator for ClusterNetworkConfig CRD.

- `ClusterNetworkConfig` CRD is here: https://github.com/giantswarm/apiextensions/pull/89
- `cluster-operator` PRs are here:
  - https://github.com/giantswarm/cluster-operator/pull/151
  - https://github.com/giantswarm/cluster-operator/pull/153

Towards https://github.com/giantswarm/giantswarm/issues/2148

### CODE REVIEW

**Comment by tuommaki** [comment]
CI is failing on `fatal: [vault1.e2e-cluster-e42067.eu-central-1.aws.gigantic.io]: FAILED! => {"changed": false, "msg": "Please export VAULT_TOKEN, ETCD_BACKUP_AWS_ACCESS_KEY and ETCD_BACKUP_AWS_SECRET_KEY"}` but my change shouldn't have anything to do with this. Any clue?

**Comment by corest** [comment]
@tuommaki it is my changes caused that. 
This PR https://github.com/giantswarm/hive/pull/302
And this https://github.com/giantswarm/giantnetes-terraform/pull/102/files
Should be merged first

**Comment by calvix** [comment]
is there something that is blocking merge?

**Comment by tuommaki** [comment]
I don't think so, now that CI is green.

**Pull request merged**
