### PR TITLE
use-multi-etcd-endpoints-instead-of-ELB

### PR DESCRIPTION
**Pull request by calvix**
remove extra elb we don't need and use multi etcd endpoint

as @mazzy89 suggested, using ELB  for etcd is not necessary as we can add multiple endpoints for etcd in calico conf, we already do the same for on-prem so we are just aligning here

### CODE REVIEW

**Comment by mazzy89** [comment]
Good one. 

I have one question. Who does ensure that etcd DNS records are in sync?


PS. Just one quick note @calvix also recommended to go with this solution here https://github.com/giantswarm/giantswarm/issues/5317#issuecomment-461936247

**Comment by calvix** [comment]
switch to use calico-typha for whole networking is out of scope of this PR, that is a big change we should properly test  and prepare for,  will probably close this PR for now

**Comment by corest** [comment]
@calvix close? PR reminder keep sending me this

**Comment by calvix** [comment]
I will give it a quick spin and see if we can easily merge it otherwise I will close it.

**Comment by calvix** [comment]
all green, nice

**Comment by kopiczko** [comment]
Are you confident about DNS propagation? This is the reason we switched back to ELB in TC.

**Comment by kopiczko** [comment]
Unless it doesn't go trough Route53.

**Comment by calvix** [comment]
> Are you confident about DNS propagation? This is the reason we switched back to ELB in TC.

Not sure about the TC but in CP we have TTL for etcd records 30 sec which is low enough to work this nicely. At least that's what I saw in tests. Let's see how it behaves in real envs.

**Pull request merged**
