### PR TITLE
Remove build dir

### PR DESCRIPTION
**Pull request by calvix**
adjust docs and e2e to remove build dir

### CODE REVIEW

**Comment by calvix** [comment]
finally this works :P

**Comment by calvix** [comment]
We need to keep the sed lien for removing the backend line, in the original e2e with build dir and `backend.tf` files we just never created proper backend configuration. Now the behavior and content are the same.

**Comment by mazzy89** [comment]
Yes the `sed` is to let to use `local` as backed rather than `s3` or `azure`

**Comment by calvix** [comment]
RFR

**Comment by calvix** [comment]
e2e failing because azure is deleting resources for 2 hours+, but otherwise all nodes are ready, merging

**Pull request merged**
