### PR TITLE
VMware VSphere Management Cluster

### PR DESCRIPTION
**Pull request by mazzy89**
This PR aims to create a management cluster on a VMWare Vsphere installation.

An NSX-T module has been created to handle networking - this can be used in the case that the VSphere account comes out with an NSX-T product. It can be disabled. In that case the user must be an already created network where attach VMs.

The NSX-T module creates all the necessary logical resources and tag them properly:

- tier 1 router (optionally)
- switch (segment)
- DHCP server (with the IP range assigned)

Masters/Workers/Vault are at the moment only VMs.

### CODE REVIEW

**Comment by mazzy89** [comment]
Tested the NSX-T creastion:

```hcl
❯ terraform apply                                                                                                                                     18:58:11

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.nsxt[0].nsxt_dhcp_server_profile.server_profile will be created
  + resource "nsxt_dhcp_server_profile" "server_profile" {
      + display_name    = (known after apply)
      + edge_cluster_id = "c9a8b572-fc43-4da9-9501-f9c07f75f95e"
      + id              = (known after apply)
      + revision        = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_dhcp_port.dhcp_port will be created
  + resource "nsxt_logical_dhcp_port" "dhcp_port" {
      + admin_state       = "UP"
      + dhcp_server_id    = (known after apply)
      + display_name      = "capv-hive-vmnet1-dhcp-server-capv-hive-lp"
      + id                = (known after apply)
      + logical_switch_id = (known after apply)
      + revision          = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_dhcp_server.dhcp_server will be created
  + resource "nsxt_logical_dhcp_server" "dhcp_server" {
      + attached_logical_port_id = (known after apply)
      + dhcp_profile_id          = (known after apply)
      + dhcp_server_ip           = "10.100.0.2/16"
      + display_name             = "dhcp-server-capv-hive"
      + id                       = (known after apply)
      + revision                 = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_port.logical_port1 will be created
  + resource "nsxt_logical_port" "logical_port1" {
      + admin_state       = "UP"
      + display_name      = "infra-capv-hive-vmnet1-lp"
      + id                = (known after apply)
      + logical_switch_id = (known after apply)
      + revision          = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_router_downlink_port.downlink_port will be created
  + resource "nsxt_logical_router_downlink_port" "downlink_port" {
      + display_name                  = "infra-capv-hive-vmnet1-dlrp"
      + id                            = (known after apply)
      + ip_address                    = "10.100.0.1/16"
      + linked_logical_switch_port_id = (known after apply)
      + logical_router_id             = (known after apply)
      + mac_address                   = (known after apply)
      + revision                      = (known after apply)
      + urpf_mode                     = "STRICT"
    }

  # module.nsxt[0].nsxt_logical_router_link_port_on_tier0.link_port_tier0 will be created
  + resource "nsxt_logical_router_link_port_on_tier0" "link_port_tier0" {
      + display_name                  = "t0-gw-t1-gw-capv-hive-t0_lrp"
      + id                            = (known after apply)
      + linked_logical_router_port_id = (known after apply)
      + logical_router_id             = "a5cc9ffb-58d3-44d2-8268-8e635bac67bb"
      + revision                      = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_router_link_port_on_tier1.link_port_tier1 will be created
  + resource "nsxt_logical_router_link_port_on_tier1" "link_port_tier1" {
      + display_name                  = "t0-gw-t1-gw-capv-hive-t1_lrp"
      + id                            = (known after apply)
      + linked_logical_router_port_id = (known after apply)
      + logical_router_id             = (known after apply)
      + revision                      = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_switch.vmnet1 will be created
  + resource "nsxt_logical_switch" "vmnet1" {
      + admin_state       = "UP"
      + display_name      = "capv-hive-vmnet1"
      + id                = (known after apply)
      + replication_mode  = "MTEP"
      + revision          = (known after apply)
      + transport_zone_id = "2bd87443-bc14-4829-886c-1c0eb9ecbda5"
      + vni               = (known after apply)
    }

  # module.nsxt[0].nsxt_logical_tier1_router.tier1_router will be created
  + resource "nsxt_logical_tier1_router" "tier1_router" {
      + advertise_config_revision   = (known after apply)
      + advertise_connected_routes  = true
      + advertise_lb_snat_ip_routes = false
      + advertise_lb_vip_routes     = true
      + advertise_nat_routes        = true
      + advertise_static_routes     = false
      + display_name                = "t1-gw-capv-hive"
      + edge_cluster_id             = "c9a8b572-fc43-4da9-9501-f9c07f75f95e"
      + enable_router_advertisement = true
      + failover_mode               = "NON_PREEMPTIVE"
      + id                          = (known after apply)
      + revision                    = (known after apply)

      + firewall_sections {
          + is_valid            = (known after apply)
          + target_display_name = (known after apply)
          + target_id           = (known after apply)
          + target_type         = (known after apply)
        }
    }

  # module.nsxt[0].nsxt_nat_rule.rule will be created
  + resource "nsxt_nat_rule" "rule" {
      + action               = "SNAT"
      + display_name         = "snat_capv-hive-vmnet1"
      + enabled              = true
      + id                   = (known after apply)
      + logging              = true
      + logical_router_id    = (known after apply)
      + match_source_network = "10.100.0.0/16"
      + nat_pass             = false
      + revision             = (known after apply)
      + rule_priority        = (known after apply)
      + translated_network   = "87.106.186.6"
    }

Plan: 10 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.nsxt[0].nsxt_dhcp_server_profile.server_profile: Creating...
module.nsxt[0].nsxt_logical_tier1_router.tier1_router: Creating...
module.nsxt[0].nsxt_logical_switch.vmnet1: Creating...
module.nsxt[0].nsxt_dhcp_server_profile.server_profile: Creation complete after 1s [id=c87572fb-f12c-49b4-a989-f3592f2985f2]
module.nsxt[0].nsxt_logical_dhcp_server.dhcp_server: Creating...
module.nsxt[0].nsxt_logical_dhcp_server.dhcp_server: Creation complete after 1s [id=e77c06b2-50b8-48ca-a165-c6fa23169bd9]
module.nsxt[0].nsxt_logical_tier1_router.tier1_router: Creation complete after 2s [id=b58010c9-d6f4-4c73-a5eb-fb4382c8c453]
module.nsxt[0].nsxt_logical_router_link_port_on_tier0.link_port_tier0: Creating...
module.nsxt[0].nsxt_logical_router_link_port_on_tier0.link_port_tier0: Creation complete after 1s [id=4e25d8a7-481a-4704-98aa-418487a93ebd]
module.nsxt[0].nsxt_logical_router_link_port_on_tier1.link_port_tier1: Creating...
module.nsxt[0].nsxt_logical_router_link_port_on_tier1.link_port_tier1: Creation complete after 1s [id=424157fb-fa2b-4b0f-a577-26d2c6868775]
module.nsxt[0].nsxt_logical_switch.vmnet1: Still creating... [10s elapsed]
module.nsxt[0].nsxt_logical_switch.vmnet1: Still creating... [20s elapsed]
module.nsxt[0].nsxt_logical_switch.vmnet1: Creation complete after 22s [id=e5e466ba-0c6f-4ee5-a118-1441da84be2b]
module.nsxt[0].nsxt_nat_rule.rule: Creating...
module.nsxt[0].nsxt_logical_dhcp_port.dhcp_port: Creating...
module.nsxt[0].nsxt_logical_port.logical_port1: Creating...
module.nsxt[0].nsxt_nat_rule.rule: Creation complete after 1s [id=2051]
module.nsxt[0].nsxt_logical_dhcp_port.dhcp_port: Creation complete after 2s [id=b627e51c-4abb-444c-88ef-58a165c12c3a]
module.nsxt[0].nsxt_logical_port.logical_port1: Creation complete after 5s [id=8569ae65-0ede-4b2c-b79b-a626b83e8c8b]
module.nsxt[0].nsxt_logical_router_downlink_port.downlink_port: Creating...
module.nsxt[0].nsxt_logical_router_downlink_port.downlink_port: Creation complete after 1s [id=4a02ae1b-3f0b-4ed5-bec9-93e74d44a21d]

Apply complete! Resources: 10 added, 0 changed, 0 destroyed.
````

**Comment by glitchcrab** [comment]
I've migrated the statefile to s3 so it works the same as with AWS.

**Comment by glitchcrab** [comment]
pinging chapter-sre for visibility, gonna merge it in now though as it's tested and working.

**Review by glitchcrab — APPROVED** [review]
:shipit:

**Pull request merged**
